services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - backend
  opa:
    image: openpolicyagent/opa
    container_name: opa
    command:
      - run
      - --server
      - --log-level
      - debug
    ports:
      - "8181:8181"
    networks:
      - backend

networks:
  backend:
    name: backend
