"""migrate_drift_026

Revision ID: a385fd678407
Revises: 58c1b2a9640f
Create Date: 2025-09-24 12:09:00.595856

"""

# revision identifiers, used by Alembic.
revision = 'a385fd678407'
down_revision = '58c1b2a9640f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade(engine_name):
    print("Upgrading {}".format(engine_name))
    upgrade_db()


def downgrade(engine_name):
    print("Downgrading {}".format(engine_name))
    downgrade_db()


def upgrade_db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'ck_clients', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_clients', 'heartbeat',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="heartbeat AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_clients', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_connect_events', 'event_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="event_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_connect_events', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_connect_events', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_counterentries', 'date_time',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="date_time AT TIME ZONE 'UTC'")
    op.drop_constraint(
        op.f('ck_counterentries_counter_id_player_id_period_date_time_key'), 'ck_counterentries',
        type_='unique', if_exists=True)
    op.create_unique_constraint(
        op.f('uq_ck_counterentries_counter_id_player_id_period_date_time'), 'ck_counterentries',
        ['counter_id', 'player_id', 'period', 'date_time'])
    op.alter_column(
        'ck_counters', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_counters', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_friend_invites', 'expiry_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="expiry_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_friend_invites', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_friend_invites', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_friendships', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_friendships', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_gamestates', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_gamestates', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_gamestateshistory', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_gamestateshistory', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_events', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_events', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_summary', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_summary', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_summaryhistory', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_summaryhistory', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_playercounters', 'last_update',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="last_update AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_playercounters', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_playercounters', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.drop_constraint(
        op.f('ck_playercounters_counter_id_player_id_key'), 'ck_playercounters', type_='unique', if_exists=True)
    op.create_unique_constraint(
        op.f('uq_ck_playercounters_counter_id_player_id'), 'ck_playercounters', ['counter_id', 'player_id'])
    op.alter_column(
        'ck_playerjournal', 'timestamp',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="timestamp AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_playerjournal', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_playerjournal', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_players', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_players', 'logon_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="logon_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_players', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.create_index(op.f('ix_ck_players_player_uuid'), 'ck_players', ['player_uuid'], unique=False)
    op.alter_column(
        'ck_tickets', 'used_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="used_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_tickets', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_tickets', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_events', 'event_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="event_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_events', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_events', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_identities', 'logon_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="logon_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_identities', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_identities', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_userroles', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_userroles', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_users', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_users', 'logon_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="logon_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_users', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machine_events', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machine_events', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machinegroups', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machinegroups', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machines', 'server_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="server_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machines', 'heartbeat_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="heartbeat_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machines', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machines', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matches', 'start_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="start_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matches', 'end_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="end_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matches', 'status_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="status_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matches', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matches', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchevents', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchevents', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchplayers', 'join_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="join_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchplayers', 'leave_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="leave_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchplayers', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchplayers', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchqueueplayers', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchqueueplayers', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchteams', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchteams', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_runconfigs', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_runconfigs', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_serverdaemoncommands', 'status_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        postgresql_using="status_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_serverdaemoncommands', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_serverdaemoncommands', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_servers', 'status_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="status_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_servers', 'heartbeat_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="heartbeat_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_servers', 'create_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_servers', 'modify_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade_db():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'gs_servers', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_servers', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_servers', 'heartbeat_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="heartbeat_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_servers', 'status_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="status_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_serverdaemoncommands', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_serverdaemoncommands', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_serverdaemoncommands', 'status_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="status_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_runconfigs', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_runconfigs', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchteams', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchteams', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchqueueplayers', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchqueueplayers', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchplayers', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchplayers', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchplayers', 'leave_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="leave_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchplayers', 'join_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="join_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchevents', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matchevents', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matches', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matches', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matches', 'status_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="status_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matches', 'end_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="end_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_matches', 'start_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="start_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machines', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machines', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machines', 'heartbeat_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="heartbeat_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machines', 'server_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="server_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machinegroups', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machinegroups', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machine_events', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'gs_machine_events', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_users', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_users', 'logon_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="logon_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_users', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_userroles', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_userroles', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_identities', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_identities', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_identities', 'logon_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="logon_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_events', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_events', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_user_events', 'event_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="event_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_tickets', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_tickets', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_tickets', 'used_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="used_date AT TIME ZONE 'UTC'")
    op.drop_index(op.f('ix_ck_players_player_uuid'), table_name='ck_players')
    op.alter_column(
        'ck_players', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_players', 'logon_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="logon_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_players', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_playerjournal', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_playerjournal', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_playerjournal', 'timestamp',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="timestamp AT TIME ZONE 'UTC'")
    op.drop_constraint(op.f('uq_ck_playercounters_counter_id_player_id'), 'ck_playercounters', type_='unique')
    op.create_unique_constraint(op.f('ck_playercounters_counter_id_player_id_key'), 'ck_playercounters',
                                ['counter_id', 'player_id'], postgresql_nulls_not_distinct=False)
    op.alter_column(
        'ck_playercounters', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_playercounters', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_playercounters', 'last_update',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="last_update AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_summaryhistory', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_summaryhistory', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_summary', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_summary', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_events', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_player_events', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_gamestateshistory', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_gamestateshistory', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_gamestates', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_gamestates', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_friendships', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_friendships', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_friend_invites', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_friend_invites', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_friend_invites', 'expiry_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        postgresql_using="expiry_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_counters', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_counters', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.drop_constraint(op.f('uq_ck_counterentries_counter_id_player_id_period_date_time'), 'ck_counterentries',
                       type_='unique')
    op.create_unique_constraint(op.f('ck_counterentries_counter_id_player_id_period_date_time_key'), 'ck_counterentries',
                                ['counter_id', 'player_id', 'period', 'date_time'], postgresql_nulls_not_distinct=False)
    op.alter_column(
        'ck_counterentries', 'date_time',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="date_time AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_connect_events', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_connect_events', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_connect_events', 'event_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="event_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_clients', 'modify_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="modify_date AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_clients', 'heartbeat',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="heartbeat AT TIME ZONE 'UTC'")
    op.alter_column(
        'ck_clients', 'create_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        postgresql_using="create_date AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###
