name: Test

on:
  workflow_call:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}

      - name: Install dependencies
        env:
          PYPI_USERNAME: ${{ secrets.DG_TWINE_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.DG_TWINE_PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          pip install wheel pipenv
          pipenv install --dev --system

      - name: Run PyTest
        run: pipenv run python -m gevent.monkey --module pytest --cov=driftbase/ --disable-warnings tests/

