name: Test

on:
  workflow_call:
  push:
    branches:
      - 'feature/**'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Setup local virtualenv
        run: |
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        env:
          POETRY_HTTP_BASIC_DIRECTIVE_USERNAME: ${{ secrets.DG_TWINE_USERNAME }}
          POETRY_HTTP_BASIC_DIRECTIVE_PASSWORD: ${{ secrets.DG_TWINE_PASSWORD }}
        run: |
          poetry install --no-root

      - name: Run PyTest
        id: test
        run: poetry run python -m gevent.monkey --module pytest --cov=driftbase/ --disable-warnings tests/
